"""v1_tables

Revision ID: a79155ac1866
Revises:
Create Date: 2026-05-01 12:30:48.423485

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a79155ac1866"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_deletion_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "scheduled_deletion_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="requested_at + 30 days",
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CANCELLED", "EXECUTED", name="account_deletion_status"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "action_execution_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("action_id", sa.UUID(), nullable=False),
        sa.Column(
            "executed_by",
            sa.Enum(
                "PATIENT_TAP", "PATIENT_VOICE_CONFIRM", "AUTO_CONFIRM", "SYSTEM", name="executed_by"
            ),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.Enum("SUCCESS", "CANCELLED", "FAILED", name="execution_result"),
            nullable=False,
        ),
        sa.Column(
            "cancel_reason",
            sa.Enum("USER_CANCELLED", "TIMEOUT", "PIPELINE_ERROR", name="cancel_reason"),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "executed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("occurrence_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_type",
            sa.Enum(
                "PATIENT",
                "CAREGIVER",
                "FAMILY",
                "CLINICIAN",
                "SYSTEM",
                "AGENT",
                name="activity_actor_type",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "CREATED",
                "EDITED",
                "DELETED",
                "COMPLETED",
                "UNDONE",
                "SKIPPED",
                "UNSKIPPED",
                name="activity_action",
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional context",
        ),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_interaction_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "model_version",
            sa.String(length=100),
            nullable=False,
            comment='e.g. "medgemma-27b-base"',
        ),
        sa.Column("input_text", sa.Text(), nullable=False),
        sa.Column("output_text", sa.Text(), nullable=False),
        sa.Column(
            "output_structured",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Parsed model output",
        ),
        sa.Column(
            "user_correction",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="If user modified AI output, what changed?",
        ),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='{"patient_id", "care_plan_id", "task_type"}',
        ),
        sa.Column("flagged_for_review", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "call_attempt_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("call_type", sa.Enum("SOS", "REGULAR", name="call_type"), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("FAMILY", "CAREGIVER", "EMERGENCY_SERVICES", name="call_target_type"),
            nullable=False,
        ),
        sa.Column(
            "target_id", sa.UUID(), nullable=True, comment="null for emergency_services (911)"
        ),
        sa.Column(
            "status",
            sa.Enum("INITIATED", "CANCELLED", "COMPLETED", name="call_status"),
            nullable=False,
        ),
        sa.Column(
            "cancel_stage",
            sa.Enum(
                "PRE_FAMILY_10S",
                "PRE_911_30S",
                "REGULAR_MODAL_TIMEOUT",
                "REGULAR_USER_CANCELLED",
                name="call_cancel_stage",
            ),
            nullable=True,
        ),
        sa.Column(
            "initiated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "caregiver_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "caregiver_id", sa.UUID(), nullable=True, comment="Populated when link is established"
        ),
        sa.Column(
            "link_code", sa.String(length=10), nullable=False, comment="6-char alphanumeric code"
        ),
        sa.Column(
            "qr_payload", sa.String(length=500), nullable=False, comment="Deep link URL for QR code"
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="created_at + 15 minutes",
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "LINKED", "EXPIRED", "UNLINKED", name="caregiver_link_status"),
            nullable=False,
        ),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unlinked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "unlinked_by",
            sa.String(length=20),
            nullable=True,
            comment="patient | caregiver | system",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_code"),
    )
    op.create_table(
        "caregiver_shifts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("caregiver_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("shift_active", sa.Boolean(), nullable=False),
        sa.Column("caregiver_phone", sa.String(length=50), nullable=True, comment="Encrypted PHI"),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "version", sa.String(length=20), nullable=False, comment="ToS/Privacy version e.g. v1.0"
        ),
        sa.Column(
            "flags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='{"accept_tos": true, "accept_privacy": true, "ack_not_emergency": true}',
        ),
        sa.Column(
            "consented_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True, comment="IPv4 or IPv6"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "PATIENT",
                "CAREGIVER",
                "FAMILY",
                "CLINICIAN",
                "SYSTEM",
                "AGENT",
                name="conv_member_actor_type",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "left_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set when connection is broken",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("INDIVIDUAL", "GROUP", name="conversation_type"), nullable=False),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=True,
            comment='Group: "Bakim Ekibim"; Individual: null',
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set when connection is broken",
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="For sorting conversations",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_summary_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("date_local", sa.Date(), nullable=False),
        sa.Column("completed_count", sa.Integer(), nullable=False),
        sa.Column("pending_count", sa.Integer(), nullable=False),
        sa.Column(
            "completed_tasks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='[{"task_id", "title", "subtype", "completed_at", "completed_by_actor_type"}]',
        ),
        sa.Column(
            "pending_tasks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment='[{"task_id", "title", "subtype"}]',
        ),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("sent_to_family_ids", postgresql.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "emergency_contacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="Patient user_id"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Encrypted PHI"),
        sa.Column(
            "relationship",
            sa.Enum("SPOUSE", "CHILD", "SIBLING", "FRIEND", "OTHER", name="ec_relationship"),
            nullable=False,
        ),
        sa.Column(
            "phone", sa.String(length=50), nullable=False, comment="Encrypted PHI, E.164 format"
        ),
        sa.Column("phone_verified", sa.Boolean(), nullable=False),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=False,
            comment="SOS call priority: 1=first, 2=second, 3=third",
        ),
        sa.Column(
            "invite_status",
            sa.Enum("PENDING", "ACCEPTED_APP_USER", "ACCEPTED_PHONE_ONLY", name="ec_invite_status"),
            nullable=False,
        ),
        sa.Column("invite_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invite_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "linked_family_user_id",
            sa.UUID(),
            nullable=True,
            comment="If this EC also has a Family App account",
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "family_availability",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_member_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "dnd", sa.Boolean(), nullable=False, comment="Do Not Disturb — set from Family App"
        ),
        sa.Column("family_phone", sa.String(length=50), nullable=True, comment="Encrypted PHI"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_profile_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "field_changed",
            sa.Enum(
                "CONDITIONS",
                "ALLERGIES",
                "MEDICATION_ADDED",
                "MEDICATION_REMOVED",
                "MEDICATION_UPDATED",
                name="health_profile_field",
            ),
            nullable=False,
        ),
        sa.Column("previous_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "changed_by_actor",
            sa.String(length=20),
            nullable=False,
            comment="patient | caregiver | family | system | ocr | portal",
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "conditions",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            comment="COND_ enum codes from ConditionCode",
        ),
        sa.Column("conditions_other_text", sa.Text(), nullable=True),
        sa.Column(
            "allergies",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            comment="ALG_ enum codes from AllergyCode",
        ),
        sa.Column(
            "allergy_flag", sa.Enum("YES", "NO", "UNKNOWN", name="allergy_flag"), nullable=False
        ),
        sa.Column(
            "allergy_notes_text", sa.Text(), nullable=True, comment="Free-text allergy notes"
        ),
        sa.Column(
            "declared_confidence",
            sa.Enum(
                "PROFESSIONALLY_DIAGNOSED",
                "SELF_DECLARED",
                "PREFER_NOT_TO_SAY",
                name="declared_confidence",
            ),
            nullable=False,
        ),
        sa.Column(
            "last_updated_by",
            sa.String(length=20),
            nullable=False,
            comment="patient | caregiver | family | system | ocr | portal",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "medication_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "name", sa.String(length=500), nullable=False, comment="Free-text medication name"
        ),
        sa.Column("dose", sa.String(length=255), nullable=True, comment="Free-text, no validation"),
        sa.Column("frequency", sa.String(length=255), nullable=True, comment="Free-text"),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISCONTINUED", "ARCHIVED", name="medication_status"),
            nullable=False,
        ),
        sa.Column(
            "data_source",
            sa.Enum(
                "MANUAL",
                "OCR_EXTRACTED",
                "INTEGRATED_PORTAL",
                "CAREGIVER",
                "FAMILY",
                "SYSTEM",
                "AGENT",
                name="data_source_medication",
            ),
            nullable=False,
        ),
        sa.Column(
            "source_provider",
            sa.String(length=100),
            nullable=True,
            comment="Portal name for V2 integrations",
        ),
        sa.Column(
            "ocr_confidence", sa.Float(), nullable=True, comment="V1+ OCR extraction confidence"
        ),
        sa.Column("created_by_actor_type", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message_read_statuses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("reader_actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "read_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_actor_type",
            sa.Enum(
                "PATIENT",
                "CAREGIVER",
                "FAMILY",
                "CLINICIAN",
                "SYSTEM",
                "AGENT",
                name="msg_sender_actor_type",
            ),
            nullable=False,
        ),
        sa.Column("sender_actor_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False, comment="Encrypted PHI — message text"),
        sa.Column("source", sa.Enum("MANUAL", "AGENT", name="message_source"), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "expires_at", sa.DateTime(timezone=True), nullable=False, comment="sent_at + 2 years"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DAILY_REPORT",
                "NEW_MESSAGE",
                "TASK_REMINDER",
                "CAREGIVER_CONNECTED",
                "CAREGIVER_DISCONNECTED",
                "EC_VERIFICATION_REMINDER",
                "SYMPTOM_REPORT_SENT",
                name="notification_type",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False, comment="Localized short title"),
        sa.Column(
            "redirect_target",
            sa.Enum("TASK_LIST", "INBOX", "SETTINGS_PRIVACY", name="notification_redirect_target"),
            nullable=False,
        ),
        sa.Column(
            "redirect_params",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Optional deep link params, e.g. conversation_id",
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "push_sent",
            sa.Boolean(),
            nullable=False,
            comment="Whether OS push notification was sent",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at_ui",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="created_at + 30 days — hidden from UI after this",
        ),
        sa.Column(
            "expires_at_db",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="created_at + 1 year — physically deleted from DB",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patient_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date_of_birth", sa.String(length=255), nullable=True, comment="Encrypted PHI"),
        sa.Column(
            "mobility_level",
            sa.String(length=50),
            nullable=True,
            comment="independent | assisted | bedridden",
        ),
        sa.Column(
            "tech_literacy", sa.String(length=50), nullable=True, comment="low | medium | high"
        ),
        sa.Column(
            "timezone",
            sa.String(length=50),
            nullable=False,
            comment="Patient timezone for all notifications and scheduling",
        ),
        sa.Column("wearable_device_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "proposed_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "TASK_COMPLETE",
                "TASK_COUNTER_INCREMENT",
                "MESSAGE_SEND",
                "CALL_TRIGGER_REGULAR",
                "CALL_TRIGGER_SOS",
                "SYMPTOM_REPORT_SEND",
                name="action_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_level", sa.Enum("LOW", "MEDIUM", "HIGH", name="risk_level"), nullable=False
        ),
        sa.Column("is_explicit_emergency", sa.Boolean(), nullable=False),
        sa.Column("requires_user_confirm", sa.Boolean(), nullable=False),
        sa.Column(
            "auto_confirm_after_sec", sa.Integer(), nullable=True, comment="Green=10, others=null"
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Action-specific data",
        ),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "push_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("platform", sa.String(length=10), nullable=False, comment="ios | android"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "red_escalation_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "trigger_text", sa.Text(), nullable=False, comment="The utterance that triggered red"
        ),
        sa.Column(
            "user_confirmed", sa.Boolean(), nullable=False, comment="Did user tap 'Call Family'?"
        ),
        sa.Column("user_cancelled", sa.Boolean(), nullable=False),
        sa.Column("timeout_occurred", sa.Boolean(), nullable=False),
        sa.Column("family_round1_called", sa.Boolean(), nullable=False),
        sa.Column("family_called_targets", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("family_answered", sa.Boolean(), nullable=False),
        sa.Column("asked_911_confirmation", sa.Boolean(), nullable=False),
        sa.Column("called_911", sa.Boolean(), nullable=False),
        sa.Column("attempt_notification_sent", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "symptom_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("raw_complaint", sa.Text(), nullable=False, comment="Patient's own words"),
        sa.Column("clarification_q1", sa.String(length=500), nullable=True),
        sa.Column("clarification_a1", sa.Text(), nullable=True),
        sa.Column("clarification_q2", sa.String(length=500), nullable=True),
        sa.Column("clarification_a2", sa.Text(), nullable=True),
        sa.Column("sent_to_family", sa.Boolean(), nullable=False),
        sa.Column("sent_to_caregiver", sa.Boolean(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_definitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "type", sa.Enum("ONE_TIME", "RECURRING", "COUNTER", name="task_type"), nullable=False
        ),
        sa.Column(
            "subtype", sa.Enum("STANDARD", "MEDICATION", name="task_subtype"), nullable=False
        ),
        sa.Column(
            "status", sa.Enum("ACTIVE", "ARCHIVED", name="task_definition_status"), nullable=False
        ),
        sa.Column(
            "created_by_actor_type",
            sa.Enum(
                "PATIENT",
                "CAREGIVER",
                "FAMILY",
                "CLINICIAN",
                "SYSTEM",
                "AGENT",
                name="task_actor_type",
            ),
            nullable=False,
        ),
        sa.Column("created_by_actor_id", sa.UUID(), nullable=False),
        sa.Column(
            "source_provenance",
            sa.Enum(
                "MANUAL", "CAREGIVER", "FAMILY", "INTEGRATED", "AGENT", name="source_provenance"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_occurrences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("date_local", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("TODO", "DONE", "SKIPPED", name="task_occurrence_status"),
            nullable=False,
        ),
        sa.Column(
            "progress_count", sa.Integer(), nullable=True, comment="For counter tasks: 0..target"
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_actor_type", sa.String(length=20), nullable=True),
        sa.Column("completed_by_actor_id", sa.UUID(), nullable=True),
        sa.Column("skipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("skipped_by_actor_type", sa.String(length=20), nullable=True),
        sa.Column("skip_reason", sa.Enum("MANUAL", name="skip_reason"), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("due_date_local", sa.Date(), nullable=True),
        sa.Column("due_time_local", sa.Time(), nullable=True),
        sa.Column(
            "frequency", sa.Enum("DAILY", "WEEKLY", name="recurrence_frequency"), nullable=True
        ),
        sa.Column(
            "days_of_week",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            comment="For weekly: [MON, WED, FRI]",
        ),
        sa.Column("time_of_day_local", sa.Time(), nullable=True),
        sa.Column("target_per_day", sa.Integer(), nullable=True),
        sa.Column("reset_rule", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True, comment="Encrypted PHI"),
        sa.Column(
            "phone", sa.String(length=50), nullable=True, comment="Encrypted PHI, E.164 format"
        ),
        sa.Column("display_name", sa.String(length=255), nullable=True, comment="Encrypted PHI"),
        sa.Column(
            "role",
            sa.Enum("PATIENT", "CAREGIVER", "FAMILY", "CLINICIAN", "ADMIN", name="user_role"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "PENDING_VERIFICATION", "DELETED", name="user_status"),
            nullable=False,
        ),
        sa.Column(
            "auth_method",
            sa.Enum("APPLE", "GOOGLE", "PHONE_OTP", name="auth_method"),
            nullable=True,
        ),
        sa.Column("locale", sa.String(length=10), nullable=False, comment="en, fr, tr"),
        sa.Column("password_hash", sa.Text(), nullable=True, comment="Argon2id hash"),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consent_version",
            sa.String(length=20),
            nullable=True,
            comment="Latest accepted ToS/Privacy version",
        ),
        sa.Column("consent_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "voice_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "trigger_source",
            sa.Enum(
                "PTT",
                "WAKEWORD_IN_APP",
                "SIRI_SHORTCUT",
                "ASSISTANT_DEEPLINK",
                name="voice_trigger_source",
            ),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("asr_transcript_raw", sa.Text(), nullable=True),
        sa.Column("asr_confidence", sa.Float(), nullable=True),
        sa.Column("llm_normalized_text", sa.Text(), nullable=True),
        sa.Column(
            "judge_category",
            sa.Enum(
                "MEDICAL_ADVICE",
                "IRRELEVANT",
                "GENERAL_LIFE",
                "IN_SCOPE_ACTION",
                name="judge_category",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PROCESSING",
                "AWAITING_USER",
                "EXECUTED",
                "CANCELLED",
                "FAILED",
                name="voice_session_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "audio_uri", sa.String(length=500), nullable=True, comment="Optional, 7-day retention"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_email", sa.String(length=255), nullable=True, comment="Encrypted PHI"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_accounts")
    op.drop_table("voice_sessions")
    op.drop_table("users")
    op.drop_table("task_schedules")
    op.drop_table("task_occurrences")
    op.drop_table("task_definitions")
    op.drop_table("symptom_reports")
    op.drop_table("red_escalation_logs")
    op.drop_table("push_tokens")
    op.drop_table("proposed_actions")
    op.drop_table("patient_profiles")
    op.drop_table("notifications")
    op.drop_table("messages")
    op.drop_table("message_read_statuses")
    op.drop_table("medication_records")
    op.drop_table("health_profiles")
    op.drop_table("health_profile_audit_logs")
    op.drop_table("family_availability")
    op.drop_table("emergency_contacts")
    op.drop_table("daily_summary_logs")
    op.drop_table("conversations")
    op.drop_table("conversation_members")
    op.drop_table("consent_records")
    op.drop_table("caregiver_shifts")
    op.drop_table("caregiver_links")
    op.drop_table("call_attempt_logs")
    op.drop_table("ai_interaction_logs")
    op.drop_table("activity_logs")
    op.drop_table("action_execution_logs")
    op.drop_table("account_deletion_requests")
    # ### end Alembic commands ###
